// <auto-generated>
// Rewired Constants
// This list was generated on 2019/11/10 15:16:10
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RN.Network.SpaceWar
{
    public static partial class PlayerInputActions
    {
        // Default
        // UI
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UI Vertical")]
        public const int UI_Vertical = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UI Horizontal")]
        public const int UI_Horizontal = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Confirm")]
        public const int Confirm = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Cancel")]
        public const int Cancel = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Exit")]
        public const int Exit = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Scores")]
        public const int Scores = 5;
        // Actor
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "Move Vertical")]
        public const int Move_Vertical = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "Move Horizontal")]
        public const int Move_Horizontal = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "Accelerate")]
        public const int Accelerate = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "Torque")]
        public const int Torque = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "Torque Left")]
        public const int Torque_Left = 10;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "Torque Right")]
        public const int Torque_Right = 11;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "MouseButton0")]
        public const int MouseButton0 = 12;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "MouseButton1")]
        public const int MouseButton1 = 13;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "MouseButton2")]
        public const int MouseButton2 = 14;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "MouseY")]
        public const int MouseY = 15;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "MouseZ")]
        public const int MouseZ = 16;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "MouseX")]
        public const int MouseX = 17;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "Uninstall")]
        public const int Shift = 18;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "Shield")]
        public const int Shield = 19;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "Weapon0")]
        public const int Weapon0 = 20;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "Weapon1")]
        public const int Weapon1 = 21;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "Weapon2")]
        public const int Weapon2 = 22;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "Weapon3")]
        public const int Weapon3 = 23;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "Weapon4")]
        public const int Weapon4 = 24;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "Weapon5")]
        public const int Weapon5 = 25;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "Weapon6")]
        public const int Weapon6 = 26;
        /*[Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "Weapon7")]
        public const int Weapon7 = 27;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "Weapon8")]
        public const int Weapon8 = 28;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "Weapon9")]
        public const int Weapon9 = 29;*/
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "AssistWeapon0")]
        public const int AssistWeapon0 = 30;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "AssistWeapon1")]
        public const int AssistWeapon1 = 31;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "AssistWeapon2")]
        public const int AssistWeapon2 = 32;
        /*[Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "AssistWeapon3")]
        public const int AssistWeapon3 = 33;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Actor", friendlyName = "AssistWeapon4")]
        public const int AssistWeapon4 = 34;*/
    }
    public static partial class InputPlayer
    {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player 0")]
        public const int Player0 = 0;
    }
}
